# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chen hao
email: 1739224217@qq.com
description: The Web of chenhao
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chenhao.shop" # the base hostname & protocol for your site
twitter_username: kilkio
github_username:  kilkio
paginate: 3
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
